default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production

staging:
  primary: &primary_staging
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_staging
  queue:
    <<: *primary_staging

development:
  primary: &primary_development
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_development
  queue:
    <<: *primary_development

test:
  primary: &primary_test
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_test
  queue:
    <<: *primary_test
